version: "2"

services:
  acntech_tomcat:
    build: .
    image: acntech/tomcat:8.5.6-alpine
    container_name: acntech-tomcat-alpine
    hostname: tomcat.acntech.internal
    ports:
      - "8080:8080"